-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 17:08:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`user` (
  `userID` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `cookie` VARCHAR(45) NULL,
  `sessionExpiration` DATETIME NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distributor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`distributor` (
  `distributorID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`distributorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`orders` (
  `transactionID` INT NOT NULL,
  `date` DATETIME NULL,
  `country` VARCHAR(45) NULL,
  `productID` INT NULL,
  `quantity` INT NULL,
  `userID` INT NOT NULL,
  `distributorID` INT NOT NULL,
  PRIMARY KEY (`transactionID`),
  INDEX `fk_orders_user_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_orders_distributor1_idx` (`distributorID` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`userID`)
    REFERENCES `db`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_distributor1`
    FOREIGN KEY (`distributorID`)
    REFERENCES `db`.`distributor` (`distributorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`listing` (
  `listingID` INT NOT NULL,
  `productID` INT NULL,
  `price` INT NULL,
  `quantity` INT NULL,
  `distributorID` INT NOT NULL,
  PRIMARY KEY (`listingID`),
  INDEX `fk_listing_distributor1_idx` (`distributorID` ASC) VISIBLE,
  CONSTRAINT `fk_listing_distributor1`
    FOREIGN KEY (`distributorID`)
    REFERENCES `db`.`distributor` (`distributorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`inventory` (
  `productID` INT NOT NULL,
  `count` INT NULL,
  `price` INT NULL,
  `distributor_distributorID` INT NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_inventory_distributor1_idx` (`distributor_distributorID` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_distributor1`
    FOREIGN KEY (`distributor_distributorID`)
    REFERENCES `db`.`distributor` (`distributorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`address` (
  `userID` INT NOT NULL,
  `streetAddress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT,
  INDEX `fk_address_user1_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `db`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


