-- create table in DB
-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 17:08:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBTeam3` DEFAULT CHARACTER SET utf8 ;
USE `DBTeam3` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeam3`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `addressLine1` VARCHAR(45) NULL,
  `addressLine2` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `cookie` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  `sessionExpiration` DATETIME NULL,
  `locked` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distributor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeam3`.`distributor` (
  `distributorID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`distributorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeam3`.`orders` (
  `transactionID` INT NOT NULL,
  `date` DATETIME NULL,
  `country` VARCHAR(45) NULL,
  `productID` INT NULL,
  `quantity` INT NULL,
  `userID` INT NOT NULL,
  `distributorID` INT NOT NULL,
  PRIMARY KEY (`transactionID`),
  INDEX `fk_orders_user_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_orders_distributor1_idx` (`distributorID` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`userID`)
    REFERENCES `DBTeam3`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_distributor1`
    FOREIGN KEY (`distributorID`)
    REFERENCES `DBTeam3`.`distributor` (`distributorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeam3`.`listing` (
  `listingID` INT NOT NULL,
  `productID` INT NULL,
  `price` INT NULL,
  `quantity` INT NULL,
  `distributorID` INT NOT NULL,
  PRIMARY KEY (`listingID`),
  INDEX `fk_listing_distributor1_idx` (`distributorID` ASC) VISIBLE,
  CONSTRAINT `fk_listing_distributor1`
    FOREIGN KEY (`distributorID`)
    REFERENCES `DBTeam3`.`distributor` (`distributorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeam3`.`inventory` (
  `productID` INT NOT NULL,
  `count` INT NULL,
  `price` INT NULL,
  `distributor_distributorID` INT NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `fk_inventory_distributor1_idx` (`distributor_distributorID` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_distributor1`
    FOREIGN KEY (`distributor_distributorID`)
    REFERENCES `DBTeam3`.`distributor` (`distributorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBTeam3`.`address` (
  `userID` INT NOT NULL,
  `streetAddress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT,
  INDEX `fk_address_user1_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `DBTeam3`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- create user called `manager` with password `Password`
CREATE USER 'manager'@'%' IDENTIFIED BY 'Password';

-- give access to manager on db
GRANT ALL PRIVILEGES ON *.* TO 'manager'@'%';

-- set password method to native password for mysql workbench access (mysql 8 issue)
ALTER USER 'manager'@'%' IDENTIFIED WITH MYSQL_NATIVE_PASSWORD BY 'Password';

-- flush them privileges
FLUSH PRIVILEGES;
